### ISSUE TITLE
[Drafts] Further improvements on the draft page.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2089]
### Describe the solution you'd like

Collection of further improvements on the draft page.
- [x] Statistic of cache types and log types (#2086)
- [x] Log type icon (maybe also as an overlaid icon over the cache type) (#2086)
- [x] Always show the time
- [x] Automatic back to Drafts
- [x] Show posted Log after logging
Beim alten Loggen hat man nach dem Absenden des Logs nochmal den Log gesehen. Gerade in Bezug auf #1688 kann das sehr hilfreich sein. Momentan muss man ja immer runterscrollen, um den eigenen Log zu sehen. Ich habe zwei Vorschläge:
1: Die alte Seite nutzen, auf die man kommen würde, wenn man mit dem alten Logform loggen würde
2: Den Log unter dem Back to Drafts Banner anzeigen
3: (In Kombination zu "Automatik back to Drafts") Über den Drafts, wenn man zu diesen zurückkehrt (würde immer ein Request benötigen)

**Comment by 2Abendsegler** [comment]
- [ ] There are also relevant points to be taken from #2047 (enter everything above).

**Comment by capoaira** [comment]
Ich denke für "Statistic of cache types and log types" könnte #645 von Ruko interessant sein. Besonders das Laden aller Caches: (sofern GS nichts geändert hat, was das verhindert...)

```js
            function drafts_scrollAndCheck(){

                var step_width = 5000;
                initial_y = $(window).scrollTop();
                $(window).scrollTop(initial_y+step_width);
                new_y = $(window).scrollTop();
                console.log($('.draft-list li').length);

                if(initial_y != new_y){
                    setTimeout(function() {
                        drafts_scrollAndCheck()
                    },1500);
                }else{
                    console.log('Done Scrolling Extracting...');
                    extractDrafts();
                }
            }
```

Im Moment habe ich aber nicht genügend Drafts, um das zu testen bzw. weiterzuentwickeln.

**Comment by capoaira** [comment]
- [ ] Show posted Log after logging
Beim alten Loggen hat man nach dem Absenden des Logs nochmal den Log gesehen. Gerade in Bezug auf #1688 kann das sehr hilfreich sein. Momentan muss man ja immer runterscrollen, um den eigenen Log zu sehen. Ich habe zwei Vorschläge:
1: Die alte Seite nutzen, auf die man kommen würde, wenn man mit dem alten Logform loggen würde
2: Den Log unter dem Back to Drafts Banner anzeigen
3: (In Kombination zu "Automatik back to Drafts") Über den Drafts, wenn man zu diesen zurückkehrt (würde immer ein Request benötigen)

**Comment by 2Abendsegler** [comment]
> Show posted Log after logging

Den neuen Punkt habe ich ganz oben mit aufgenommen.

> 1: Die alte Seite nutzen, auf die man kommen würde, wenn man mit dem alten Logform loggen würde

Das würde ich am Besten finden.

> Morgen kommen hoffentlich genug Drafts zusammen, um hier weiter zu machen ;)

Ich werde jetzt trotzdem mal eine neue Version raushauen.

**Comment by capoaira** [comment]
Ich werde es voraussichtlich nicht so schnell schaffen, hier noch den letzten Punkt zu implementieren. @2Abendsegler, wenn du die Zeit hast, kannst du dich gerne hier ran setzten ;)
Soweit ich mich erinnere, war mein Problem, dass man nicht direkt die Log-Ansicht vom alten Loggen nutzen kann. Man müsste also die generelle Logansicht nutzen und den Back to Drafts Button selbst einfügen.

PS.: Ich habe die Filtersets vom Meilenstein entfernt, vermutlich komme ich erst nach meinem Semester wieder dazu, selber zu coden...

**Comment by 2Abendsegler** [comment]
Danke für die Info. Ich werde sehen was geht. Vielleicht kann ich mir in Zukunft auch wieder etwas mehr Zeit nehmen um hier etwas zu tun.

**Comment by 2Abendsegler** [comment]
Der letzte Punkt "Show posted Log after logging" wird über Issue #2208 behandelt. 
Relevante Punkte aus der Diskussion #2047 gibt es auch nicht mehr.
Ich schließe das Issue.
