### ISSUE TITLE
Milestone 0.9.12

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#829]
Mit diesem Issue können wir den Release vom Milestone 0.9.12 planen.

@Ruko2010 @2Abendsegler

**Comment by CachingFoX** [comment]
Ich versuche noch Issue #818 und #819 fertig zu bekommen

**Comment by 2Abendsegler** [comment]
Ich hab nichts mehr bis auf den PR zu #831.

**Comment by Ruko2010** [comment]
Ich werde heute Abend die bestehenden (fertigen) PRs mergen und dann schauen wir was offen ist. Wenn ihr sagt, ihr braucht noch ein paar Tage ist das auch ok, dann warte ich. Ich bin nur ab Samstag eine Woche im Urlaub und würde den Release gern vorher machen.

**Comment by 2Abendsegler** [comment]
Nein, Dringendes scheint mir nicht mehr da zu sein.

- [ ] Bitte noch PQ #837 mergen.
- [ ] Ich bau die List of PQ noch um, falls du noch so viel Zeit hast. Bin schon fast fertig. Issue #830 habe ich wieder geöffnet. Dazu kommt dann noch ein PR. Den dann bitte auch noch mergen.
- [ ] Ich bau noch für meine Dinge das Changelog auf und setzt die Installations Zähler noch zurück. Dazu kommt dann auch noch ein PR. Den dann bitte auch noch mergen.

**Comment by Ruko2010** [comment]
ok, dann mach ich die Changelogs nur für die Sachen von Fox und mir...

**Comment by Ruko2010** [comment]
Ich hab die Changelogs fertig. Ich habe auch mal wieder Screenshots rein genommen, aber nur für "features".
Ich mach dann die neue Version Morgen fertig. Es sollte alles soweit vorbereitet sein. Also lass dir ruhig Zeit.

**Comment by 2Abendsegler** [comment]
- [x] Issue #830 hab ich wieder geschlossen und mit #835 weiter gearbeitet.
- [x] Hab #835 "Show both tabs "Active Pocket Queries" and "Pocket Queries Ready for Download" together of one page. # versehentlich direkt in den collector geladen. Anschließend hab ichs nochmal regulär per PR eingespielt. Es ist nichts kaputtgegangen. 
- [ ] Bitte meine Änderungen zu #835 prüfen, ob wir sie so lassen können.

Ich mach heute nur Scheiß, schon die ganze Zeit. Ich werde noch die config_standard.txt anpassen und mergen und dann werde ich nichts mehr machen.

- [ ] Kannst Du bitte meine Changelog Einträge einbauen? Zwei Bilder dazu befinden sich im Issue, falls du sie verwenden möchtest.

**Comment by 2Abendsegler** [comment]
- [ ] Bitte noch Issue #835 schließen wenn du es geprüft hast.

**Comment by Ruko2010** [comment]
Ich bau das Changelog noch auf, dann kann die neue Version ja doch noch heute raus 😃. Du bist soweit durch?

**Comment by 2Abendsegler** [comment]
Danke.
Ich bin durch. Installationzähler zurücksetzen mach ich nicht mehr.

**Comment by Ruko2010** [comment]
So, neue Version ist draußen. Ich hoffe ich habe alles im Changelog erfasst und richtig zugeordnet 😃
